// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGQwO-FHEGgE5G_rUeEvfq8R4mMbtft7k',
    appId: '1:599603550613:android:762d4b37a98a735f1a3e9c',
    messagingSenderId: '599603550613',
    projectId: 'e-blood-c2ab6',
    storageBucket: 'e-blood-c2ab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3hlP00HOvd14pM3UqWJOzLS3IFmTONn8',
    appId: '1:599603550613:ios:3d45043a6c8b1be31a3e9c',
    messagingSenderId: '599603550613',
    projectId: 'e-blood-c2ab6',
    storageBucket: 'e-blood-c2ab6.appspot.com',
    iosClientId: '599603550613-2545cgrgqs36noic7p3433r5juq2sgja.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBlood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3hlP00HOvd14pM3UqWJOzLS3IFmTONn8',
    appId: '1:599603550613:ios:3d45043a6c8b1be31a3e9c',
    messagingSenderId: '599603550613',
    projectId: 'e-blood-c2ab6',
    storageBucket: 'e-blood-c2ab6.appspot.com',
    iosClientId: '599603550613-2545cgrgqs36noic7p3433r5juq2sgja.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBlood',
  );
}
